import type { IPostItem } from 'src/types/blog';

// ----------------------------------------------------------------------

const AVATAR_PATH = '/assets/images/mock/avatar';

export const BLOG_MOCK: IPostItem[] = [
  // --- EVENTOS (7 Posts) ---
  {
    id: '1',
    title: 'Pesagem Oficial FFC 10: Encaradas tensas e promessa de nocaute',
    slug: 'pesagem-oficial-ffc-10',
    description: 'Os ânimos ficaram exaltados na última encarada antes da disputa do cinturão peso-pesado.',
    content: `<p>A cerimônia de pesagem do FFC 10 entrou para a história com uma das encaradas mais tensas de todos os tempos. Os dois desafiantes pelo cinturão quase chegaram às vias de fato antes mesmo de entrarem no cage.</p>`,
    coverUrl: '/assets/images/mock/cover/cover-1.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date().toISOString(),
    totalViews: 15400,
    totalShares: 850,
    totalComments: 45,
    totalFavorites: 320,
    metaTitle: 'Pesagem Oficial FFC 10 | Final Fight Combat',
    metaDescription: 'Veja tudo o que rolou na pesagem do maior evento do ano.',
    metaKeywords: ['Pesagem', 'FFC 10', 'MMA'],
    tags: ['Eventos', 'Pesagem', 'Cinturão'],
    featured: true,
    author: { name: 'Equipe FFC', avatarUrl: `${AVATAR_PATH}/avatar-1.webp` },
    comments: [],
    favoritePerson: [{ name: 'Fã Clube FFC', avatarUrl: `${AVATAR_PATH}/avatar-2.webp` }],
  },
  {
    id: '2',
    title: 'Resultados do Card Preliminar: Finalizações surpreendentes',
    slug: 'resultados-card-preliminar',
    description: 'Um resumo das lutas que aqueceram a noite no FFC 9.',
    content: '<p>O card preliminar não decepcionou, com três finalizações no primeiro round e nocautes fulminantes.</p>',
    coverUrl: '/assets/images/mock/cover/cover-2.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    totalViews: 8900,
    totalShares: 120,
    totalComments: 12,
    totalFavorites: 420,
    metaTitle: 'Resultados FFC 9 | Final Fight Combat',
    metaDescription: 'Card preliminar entregou lutas eletrizantes.',
    metaKeywords: ['Resultados', 'FFC 9', 'MMA'],
    tags: ['Resultados', 'Lutas'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-3.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '3',
    title: 'Bônus da Noite: Quem levou os R$ 100 mil no Grand Prix?',
    slug: 'bonus-da-noite-grand-prix',
    description: 'Anunciados os vencedores de Performance da Noite e Luta da Noite.',
    content: '<p>A organização foi generosa e distribuiu bônus para os atletas que mais se destacaram no GP.</p>',
    coverUrl: '/assets/images/mock/cover/cover-3.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    totalViews: 6500,
    totalShares: 300,
    totalComments: 8,
    totalFavorites: 150,
    metaTitle: 'Bônus da Noite FFC | Final Fight Combat',
    metaDescription: 'Veja quem levou os 100k pra casa.',
    metaKeywords: ['Bônus', 'Grand Prix', 'Premiação'],
    tags: ['GP', 'Premiação'],
    author: { name: 'Equipe FFC', avatarUrl: `${AVATAR_PATH}/avatar-4.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '4',
    title: 'Ingressos Esgotados para a Grande Final em São Paulo',
    slug: 'ingressos-esgotados-final',
    description: 'A arena lotada espera para ver o maior confronto de artes marciais mistas do ano.',
    content: '<p>A expectativa é tão alta que todos os 15.000 ingressos sumiram das bilheterias em apenas 4 horas.</p>',
    coverUrl: '/assets/images/mock/cover/cover-4.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    totalViews: 12100,
    totalShares: 450,
    totalComments: 22,
    totalFavorites: 540,
    metaTitle: 'Ingressos Esgotados | Final Fight Combat',
    metaDescription: 'Arena lotada para o FFC SP.',
    metaKeywords: ['Ingressos', 'FFC SP', 'Arena'],
    tags: ['Eventos', 'SP'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-5.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '5',
    title: 'Vaza o Pôster Oficial do Evento de Fim de Ano',
    slug: 'poster-oficial-evento-fim-de-ano',
    description: 'A rivalidade histórica reacendida: O pôster já dá o tom da disputa.',
    content: '<p>Os organizadores não queriam liberar a imagem agora, mas o vazamento apenas aumentou o hype.</p>',
    coverUrl: '/assets/images/mock/cover/cover-5.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    totalViews: 9800,
    totalShares: 210,
    totalComments: 15,
    totalFavorites: 320,
    metaTitle: 'Pôster FFC | Final Fight Combat',
    metaDescription: 'Pôster vazado do evento principal.',
    metaKeywords: ['Pôster', 'MMA', 'Evento'],
    tags: ['Notícias', 'Marketing'],
    author: { name: 'João Lutas', avatarUrl: `${AVATAR_PATH}/avatar-6.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '6',
    title: 'Mudança de Última Hora no Card Principal',
    slug: 'mudanca-ultima-hora-card',
    description: 'Lesão força substituição em uma das lutas mais aguardadas da noite.',
    content: '<p>Infelizmente, lesões fazem parte do esporte de contato, e o FFC teve que reorganizar o card às pressas.</p>',
    coverUrl: '/assets/images/mock/cover/cover-6.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    totalViews: 4500,
    totalShares: 180,
    totalComments: 9,
    totalFavorites: 110,
    metaTitle: 'Mudança no Card | Final Fight Combat',
    metaDescription: 'Substituição no evento de amanhã.',
    metaKeywords: ['Lesão', 'Card Principal', 'Substituição'],
    tags: ['Lutadores', 'Lesão'],
    author: { name: 'Maria Combate', avatarUrl: `${AVATAR_PATH}/avatar-7.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '7',
    title: 'Cobertura Completa: Tudo sobre o Evento Numerado',
    slug: 'cobertura-completa-evento-numerado',
    description: 'Links, horários e onde assistir o maior espetáculo de lutas.',
    content: '<p>Prepare a pipoca e reúna os amigos: hoje tem porrada com a transmissão completa do FFC.</p>',
    coverUrl: '/assets/images/mock/cover/cover-7.webp',
    category: 'Eventos',
    status: 'published',
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    totalViews: 18000,
    totalShares: 1500,
    totalComments: 85,
    totalFavorites: 1200,
    metaTitle: 'Onde Assistir | Final Fight Combat',
    metaDescription: 'Como acompanhar o FFC Ao Vivo.',
    metaKeywords: ['Transmissão', 'Ao Vivo', 'PPV'],
    tags: ['Transmissão', 'Ao Vivo'],
    author: { name: 'Equipe FFC', avatarUrl: `${AVATAR_PATH}/avatar-8.webp` },
    comments: [],
    favoritePerson: [],
  },

  // --- ATLETAS (7 Posts) ---
  {
    id: '8',
    title: 'De Volta ao Octógono: A Recuperação Incrível de Marcos "Marreta"',
    slug: 'recuperacao-marcos-marreta',
    description: 'Após lesão grave no joelho, o ex-campeão anuncia seu retorno ao cage.',
    content: '<p>Ninguém acreditava que ele voltaria a lutar em alto nível após a cirurgia...</p>',
    coverUrl: '/assets/images/mock/cover/cover-8.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    totalViews: 9800,
    totalShares: 400,
    totalComments: 18,
    totalFavorites: 290,
    metaTitle: 'Retorno de Marreta | FFC',
    metaDescription: 'A superação do atleta brasileiro.',
    metaKeywords: ['Atletas', 'Retorno', 'Superação'],
    tags: ['Superação', 'Atletas'],
    author: { name: 'João Lutas', avatarUrl: `${AVATAR_PATH}/avatar-9.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '9',
    title: 'Estrela em Ascensão: O Fenômeno de 20 anos que assombra a categoria',
    slug: 'fenomeno-20-anos',
    description: 'Com 5 vitórias no primeiro round, a jovem promessa quer lutar pelo cinturão ainda este ano.',
    content: '<p>A força explosiva aliada a uma técnica de Muay Thai refinada fazem dele o prospecto número um.</p>',
    coverUrl: '/assets/images/mock/cover/cover-9.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    totalViews: 5400,
    totalShares: 150,
    totalComments: 5,
    totalFavorites: 120,
    metaTitle: 'Jovem Promessa | FFC',
    metaDescription: 'Novo prospecto do MMA brasileiro.',
    metaKeywords: ['Prospecto', 'Promessa', 'MMA'],
    tags: ['Prospectos', 'Novatos'],
    author: { name: 'Maria Combate', avatarUrl: `${AVATAR_PATH}/avatar-10.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '10',
    title: 'Aposentadoria de Lenda do MMA gera comoção entre fãs',
    slug: 'aposentadoria-lenda',
    description: 'Após 20 anos de carreira, o veterano pendura as luvas dentro do octógono do FFC.',
    content: '<p>Um momento emocionante de respeito mútuo, onde todos aplaudiram de pé a trajetória do guerreiro.</p>',
    coverUrl: '/assets/images/mock/cover/cover-10.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    totalViews: 3200,
    totalShares: 90,
    totalComments: 2,
    totalFavorites: 85,
    metaTitle: 'Aposentadoria | FFC',
    metaDescription: 'Despedida de uma lenda.',
    metaKeywords: ['Aposentadoria', 'Lenda', 'Despedida'],
    tags: ['Lendas', 'Homenagem'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-11.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '17',
    title: 'Entrevista Exclusiva com o Campeão Peso Leve',
    slug: 'entrevista-exclusiva-campeao',
    description: 'Ele fala sobre o peso de carregar o cinturão e seu próximo desafiante.',
    content: '<p>Descubra como é a mentalidade inabalável do lutador mais dominante da categoria atual.</p>',
    coverUrl: '/assets/images/mock/cover/cover-11.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    totalViews: 6700,
    totalShares: 210,
    totalComments: 14,
    totalFavorites: 320,
    metaTitle: 'Entrevista Exclusiva | FFC',
    metaDescription: 'O que o campeão pensa sobre seu rival.',
    metaKeywords: ['Entrevista', 'Campeão', 'MMA'],
    tags: ['Entrevista', 'Cinturão'],
    author: { name: 'João Lutas', avatarUrl: `${AVATAR_PATH}/avatar-12.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '18',
    title: 'As Maiores Rivalidades Atuais no Plantel do FFC',
    slug: 'maiores-rivalidade-ffc',
    description: 'Atletas que simplesmente não conseguem dividir o mesmo ar e estão destinados a se colidir.',
    content: '<p>Rivalidade vende, mas quando é real, os golpes dentro da arena carregam uma intenção diferente.</p>',
    coverUrl: '/assets/images/mock/cover/cover-12.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    totalViews: 4100,
    totalShares: 120,
    totalComments: 3,
    totalFavorites: 95,
    metaTitle: 'Rivalidades | FFC',
    metaDescription: 'Inimigos fora e dentro do cage.',
    metaKeywords: ['Rivalidade', 'Trash Talk', 'MMA'],
    tags: ['Rivalidade', 'Atletas'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-13.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '19',
    title: 'Mudança de Categoria: Por que tantos atletas estão subindo de peso?',
    slug: 'mudanca-categoria-peso',
    description: 'A dificuldade extrema do corte de peso e a busca por mais potência nos golpes.',
    content: '<p>Lutar em sua categoria natural virou a nova moda, preservando a saúde e ganhando queixo de ferro.</p>',
    coverUrl: '/assets/images/mock/cover/cover-13.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    totalViews: 8900,
    totalShares: 500,
    totalComments: 28,
    totalFavorites: 450,
    metaTitle: 'Mudança de Categoria | FFC',
    metaDescription: 'Corte de peso e saúde.',
    metaKeywords: ['Corte de Peso', 'Categoria', 'Nutrição'],
    tags: ['Nutrição', 'Atletas'],
    author: { name: 'Dr. Esportivo', avatarUrl: `${AVATAR_PATH}/avatar-14.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '20',
    title: 'A Nova Safra do Jiu-Jitsu Brasileiro que invadiu o MMA',
    slug: 'nova-safra-bjj-mma',
    description: 'Focados não apenas em submeter, mas em sobreviver à porrada em pé.',
    content: '<p>O Jiu-Jitsu adaptado para o MMA moderno é dinâmico, buscando a queda sem esquecer a trocação.</p>',
    coverUrl: '/assets/images/mock/cover/cover-14.webp',
    category: 'Atletas',
    status: 'published',
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    totalViews: 3500,
    totalShares: 80,
    totalComments: 2,
    totalFavorites: 70,
    metaTitle: 'BJJ no MMA | FFC',
    metaDescription: 'Transição das faixas coloridas para as luvas.',
    metaKeywords: ['BJJ', 'Jiu-Jitsu', 'MMA'],
    tags: ['BJJ', 'Adaptação'],
    author: { name: 'Mestre da Arte', avatarUrl: `${AVATAR_PATH}/avatar-15.webp` },
    comments: [],
    favoritePerson: [],
  },

  // --- TÉCNICAS (7 Posts) ---
  {
    id: '11',
    title: 'Anatomia de um Nocaute: A Física por Trás do Cruzado de Direita',
    slug: 'anatomia-nocaute-cruzado',
    description: 'Como o torque do quadril se transforma em energia de impacto devastador.',
    content: '<p>Nocautear exige mais do que força; é uma questão de alavancas, transferência de peso e precisão.</p>',
    coverUrl: '/assets/images/mock/cover/cover-15.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    totalViews: 18500,
    totalShares: 1200,
    totalComments: 95,
    totalFavorites: 890,
    metaTitle: 'Anatomia Nocaute | FFC',
    metaDescription: 'A ciência da trocação.',
    metaKeywords: ['Nocaute', 'Ciência', 'Técnica'],
    tags: ['Trocacão', 'Striking'],
    author: { name: 'Mestre da Arte', avatarUrl: `${AVATAR_PATH}/avatar-16.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '12',
    title: 'Como Defender o Single Leg: Dicas de Wrestling para Iniciantes',
    slug: 'defender-single-leg',
    description: 'A diferença entre ser amassado no chão ou manter a luta em pé.',
    content: '<p>A postura correta e o sprawl são fundamentais contra quedas bem ensaiadas no MMA.</p>',
    coverUrl: '/assets/images/mock/cover/cover-16.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 129600000).toISOString(),
    totalViews: 7100,
    totalShares: 340,
    totalComments: 25,
    totalFavorites: 410,
    metaTitle: 'Defesa de Queda | FFC',
    metaDescription: 'Aprenda a defender quedas.',
    metaKeywords: ['Wrestling', 'Queda', 'Sprawl'],
    tags: ['Wrestling', 'Defesa'],
    author: { name: 'Coach Tático', avatarUrl: `${AVATAR_PATH}/avatar-17.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '13',
    title: 'Triângulo de Mão: A finalização favorita da nova geração',
    slug: 'triangulo-de-mao-nova-geracao',
    description: 'Por que esta técnica sem kimono se tornou a submissão mais temida do card.',
    content: '<p>Um estrangulamento silencioso que muitas vezes surpreende lutadores cansados no final do round.</p>',
    coverUrl: '/assets/images/mock/cover/cover-17.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 216000000).toISOString(),
    totalViews: 4200,
    totalShares: 110,
    totalComments: 6,
    totalFavorites: 135,
    metaTitle: 'Triângulo de Mão | FFC',
    metaDescription: 'Domine a finalização letal.',
    metaKeywords: ['Finalização', 'Submissão', 'BJJ'],
    tags: ['Grappling', 'Submissão'],
    author: { name: 'Equipe FFC', avatarUrl: `${AVATAR_PATH}/avatar-18.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '21',
    title: 'O Calf Kick Mudou o Esporte: Como chutar sem ser bloqueado',
    slug: 'calf-kick-esporte',
    description: 'A evolução dos chutes baixos que miram a panturrilha em vez da coxa.',
    content: '<p>Os lutadores tradicionais tiveram que refazer suas bases para não saírem mancando das lutas.</p>',
    coverUrl: '/assets/images/mock/cover/cover-18.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 302400000).toISOString(),
    totalViews: 5900,
    totalShares: 180,
    totalComments: 8,
    totalFavorites: 210,
    metaTitle: 'Chute na Panturrilha | FFC',
    metaDescription: 'O chute que destrói pernas.',
    metaKeywords: ['Calf Kick', 'Muay Thai', 'MMA'],
    tags: ['Muay Thai', 'Evolução'],
    author: { name: 'Maria Combate', avatarUrl: `${AVATAR_PATH}/avatar-19.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '22',
    title: 'A Importância do Jab no Controle do Octógono',
    slug: 'importancia-do-jab-octogono',
    description: 'O soco mais rápido e seguro para medir a distância e iniciar sequências.',
    content: '<p>Quem tem um bom jab, tem a chave para controlar o ritmo e o alcance da luta inteira.</p>',
    coverUrl: '/assets/images/mock/cover/cover-20.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 388800000).toISOString(),
    totalViews: 9200,
    totalShares: 420,
    totalComments: 31,
    totalFavorites: 560,
    metaTitle: 'Controle de Octógono | FFC',
    metaDescription: 'Como o Boxe se adapta ao MMA.',
    metaKeywords: ['Boxe', 'Jab', 'Distância'],
    tags: ['Boxe', 'Fundamentos'],
    author: { name: 'João Lutas', avatarUrl: `${AVATAR_PATH}/avatar-20.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '23',
    title: 'Recuperação Ativa: Crioterapia e Banheira de Gelo',
    slug: 'recuperacao-ativa-gelo',
    description: 'Os métodos científicos que permitem aos atletas treinar três vezes ao dia.',
    content: '<p>Seu corpo não cresce no treino, cresce no descanso. E o gelo é o melhor amigo de quem sente dor.</p>',
    coverUrl: '/assets/images/mock/cover/cover-21.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 475200000).toISOString(),
    totalViews: 11000,
    totalShares: 800,
    totalComments: 45,
    totalFavorites: 920,
    metaTitle: 'Recuperação Ativa | FFC',
    metaDescription: 'Ciência a favor da luta.',
    metaKeywords: ['Crioterapia', 'Recuperação', 'Fisioterapia'],
    tags: ['Medicina', 'Performance'],
    author: { name: 'Dr. Esportivo', avatarUrl: `${AVATAR_PATH}/avatar-21.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '24',
    title: 'Análise de Luta: Como o Desafiante anulou o jogo do Campeão',
    slug: 'analise-luta-desafiante',
    description: 'Um estudo estratégico de movimentação lateral e contragolpes de encontro.',
    content: '<p>Vamos destrinchar em quadros lentos como a estratégia do azarão o transformou no novo dono do cinturão.</p>',
    coverUrl: '/assets/images/mock/cover/cover-22.webp',
    category: 'Técnicas',
    status: 'published',
    createdAt: new Date(Date.now() - 561600000).toISOString(),
    totalViews: 6300,
    totalShares: 150,
    totalComments: 9,
    totalFavorites: 180,
    metaTitle: 'Análise Estratégica | FFC',
    metaDescription: 'Dissecando o Main Event.',
    metaKeywords: ['Análise', 'Estratégia', 'Tática'],
    tags: ['Estudos', 'Tática'],
    author: { name: 'Coach Tático', avatarUrl: `${AVATAR_PATH}/avatar-22.webp` },
    comments: [],
    favoritePerson: [],
  },

  // --- BASTIDORES (7 Posts) ---
  {
    id: '14',
    title: 'O Vestiário Minutos Antes do Main Event',
    slug: 'vestiario-minutos-antes-main-event',
    description: 'O silêncio, a música alta, as fitas e a adrenalina concentrada nas mãos e mentes.',
    content: '<p>Cada atleta reage diferente à iminência da guerra. Entramos nos vestiários para registrar a tensão.</p>',
    coverUrl: '/assets/images/mock/cover/cover-23.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    totalViews: 12500,
    totalShares: 900,
    totalComments: 55,
    totalFavorites: 670,
    metaTitle: 'Vestiários FFC | FFC',
    metaDescription: 'Momentos antes de pisar na arena.',
    metaKeywords: ['Bastidores', 'Vestiário', 'Foco'],
    tags: ['Bastidores', 'Mentalidade'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-23.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '15',
    title: 'A Vida de um Cutman: Estancando sangue na beira da grade',
    slug: 'vida-de-um-cutman',
    description: 'Os anônimos que mantêm os lutadores inteiros entre os rounds.',
    content: '<p>Eles têm 60 segundos com vaselina e gelo para parar hemorragias que definirão o destino da luta.</p>',
    coverUrl: '/assets/images/mock/cover/cover-24.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    totalViews: 5800,
    totalShares: 220,
    totalComments: 12,
    totalFavorites: 190,
    metaTitle: 'Heróis Anônimos | FFC',
    metaDescription: 'O papel do cutman no evento.',
    metaKeywords: ['Cutman', 'Sangue', 'Bastidores'],
    tags: ['Cutman', 'Staff'],
    author: { name: 'Dr. Esportivo', avatarUrl: `${AVATAR_PATH}/avatar-24.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '16',
    title: 'O Processo de Produção do Card de TV',
    slug: 'processo-producao-card-tv',
    description: 'Mais de 100 profissionais envolvidos para que a porrada chegue na sua sala.',
    content: '<p>Câmeras a cabo, iluminação scifi, gruas e muito suor. Assim se cria o espetáculo visual do FFC.</p>',
    coverUrl: '/assets/images/mock/cover/cover-5.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    totalViews: 8100,
    totalShares: 410,
    totalComments: 30,
    totalFavorites: 295,
    metaTitle: 'Produção FFC | FFC',
    metaDescription: 'Como o FFC é transmitido.',
    metaKeywords: ['Produção', 'TV', 'Broadcasting'],
    tags: ['Transmissão', 'Mídia'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-6.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '25',
    title: 'Contratos e Patrocínios: A Nova Era de Ouro dos Atletas de MMA',
    slug: 'contratos-patrocinios-mma',
    description: 'Como o FFC está liderando os pagamentos e dividindo a receita do PPV.',
    content: '<p>O valorizaçao financeira dos lutadores finalmente chegou a um patamar aceitável na indústria.</p>',
    coverUrl: '/assets/images/mock/cover/cover-6.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    totalViews: 14000,
    totalShares: 1100,
    totalComments: 62,
    totalFavorites: 980,
    metaTitle: 'Pagamento Atletas | FFC',
    metaDescription: 'Patrocínios e bolsas no FFC.',
    metaKeywords: ['Pagamento', 'Bolsa', 'Patrocínio'],
    tags: ['Negócios', 'Patrocínio'],
    author: { name: 'Equipe FFC', avatarUrl: `${AVATAR_PATH}/avatar-11.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '26',
    title: 'A Rígida Comissão Atlética: Exames Antidoping e Pesagens Surpresa',
    slug: 'comissao-atletica-doping',
    description: 'Como garantimos que as lutas do FFC são 100% limpas e justas.',
    content: '<p>Onde e quando a comissão quiser, o atleta deve estar pronto para oferecer suas amostras de sangue.</p>',
    coverUrl: '/assets/images/mock/cover/cover-7.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    totalViews: 5200,
    totalShares: 140,
    totalComments: 4,
    totalFavorites: 115,
    metaTitle: 'Testes Antidoping | FFC',
    metaDescription: 'Políticas do FFC contra trapaças.',
    metaKeywords: ['Doping', 'Testes', 'Justiça'],
    tags: ['Regulação', 'Doping'],
    author: { name: 'Dr. Esportivo', avatarUrl: `${AVATAR_PATH}/avatar-10.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '27',
    title: 'O Fim da Noite: Festas Oficiais e Hospitais',
    slug: 'fim-da-noite-festas-hospitais',
    description: 'O contraste entre quem ganha o bônus na balada e quem vai levar pontos no nariz.',
    content: '<p>Enquanto a arena apaga suas luzes, as duas realidades extremas do MMA se mostram cruelmente visíveis.</p>',
    coverUrl: '/assets/images/mock/cover/cover-8.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    totalViews: 7300,
    totalShares: 280,
    totalComments: 19,
    totalFavorites: 310,
    metaTitle: 'Pós Evento | FFC',
    metaDescription: 'O lado sombrio e o lado de ouro.',
    metaKeywords: ['Afterparty', 'Hospital', 'Bastidores'],
    tags: ['Bastidores', 'Realidade'],
    author: { name: 'Maria Combate', avatarUrl: `${AVATAR_PATH}/avatar-9.webp` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '28',
    title: 'Matchmaking: Como Casamos as Lutas Mais Emocionantes',
    slug: 'matchmaking-lutas-emocionantes',
    description: 'Os bastidores de quem decide quem vai bater em quem na próxima edição.',
    content: '<p>Leva-se em conta ranking, hype, estilo de luta (striker vs grappler) e contratos. Casar luta é uma arte.</p>',
    coverUrl: '/assets/images/mock/cover/cover-9.webp',
    category: 'Bastidores',
    status: 'published',
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    totalViews: 4900,
    totalShares: 160,
    totalComments: 8,
    totalFavorites: 145,
    metaTitle: 'Matchmaking | FFC',
    metaDescription: 'Como as lutas são montadas.',
    metaKeywords: ['Matchmaker', 'Organização', 'Lutas'],
    tags: ['Organização', 'Negócios'],
    author: { name: 'Equipe Editorial', avatarUrl: `${AVATAR_PATH}/avatar-8.webp` },
    comments: [],
    favoritePerson: [],
  },
];

export const COMMUNITIES_MOCK = [
  {
    name: 'MMA Fighting',
    logo: '/assets/icons/communities/mmafighting.svg', // Assuma fallbacks de logo ou ícones genéricos se não tiver imagem
    url: 'https://mmafighting.com',
  },
  {
    name: 'UFC Oficial',
    logo: '/assets/icons/communities/ufc.svg',
    url: 'https://ufc.com',
  },
  { name: 'PFL MMA', logo: '/assets/icons/communities/pfl.svg', url: 'https://pflmma.com' },
  { name: 'Sherdog', logo: '/assets/icons/communities/sherdog.svg', url: 'https://sherdog.com' },
  {
    name: 'Tatame',
    logo: '/assets/icons/communities/tatame.svg',
    url: 'https://tatame.com.br',
  },
  {
    name: 'Combate',
    logo: '/assets/icons/communities/combate.svg',
    url: 'https://ge.globo.com/combate/',
  },
];

export const VIDEOS_MOCK = {
  brazil: [
    {
      id: 'zJ1h0h5nJmE', // Placeholder youtube ids
      title: 'Melhores Momentos: FFC 10 - Nocautes Brutais',
      channel: 'FFC Oficial',
      thumbnail: 'https://img.youtube.com/vi/zJ1h0h5nJmE/maxresdefault.jpg',
      postedAt: '2 dias atrás',
      duration: '12:40',
    },
    {
      id: '1vO8B04rYt0',
      title: '🔥 Treino Aberto: Os desafios de cortar peso',
      channel: 'Sexto Round',
      thumbnail: 'https://img.youtube.com/vi/1vO8B04rYt0/maxresdefault.jpg',
      postedAt: '5 horas atrás',
      duration: '08:15',
    },
    {
      id: 'X-2_s-P3p5k',
      title: 'URGENTE: A Lesão que mudou tudo no Main Event',
      channel: 'MMA Hoje',
      thumbnail: 'https://img.youtube.com/vi/X-2_s-P3p5k/maxresdefault.jpg',
      postedAt: '1 dia atrás',
      duration: '15:20',
    },
    {
      id: 'QeQ29R2m3Fw',
      title: 'ENTREVISTA: "Eu vou arrancar a cabeça dele"',
      channel: 'Papo de Luta',
      thumbnail: 'https://img.youtube.com/vi/QeQ29R2m3Fw/maxresdefault.jpg',
      postedAt: '3 dias atrás',
      duration: '22:00',
    },
  ],
  international: [
    {
      id: '6l3bI89y6vY',
      title: 'Strategy Breakdown: How to defend the Calf Kick',
      channel: 'Luke Thomas',
      thumbnail: 'https://img.youtube.com/vi/6l3bI89y6vY/maxresdefault.jpg',
      postedAt: '1 dia atrás',
      duration: '18:10',
    },
    {
      id: 'T5R2XGzL4H8',
      title: 'Post-Fight Press Conference: Full Video',
      channel: 'MMA Junkie',
      thumbnail: 'https://img.youtube.com/vi/T5R2XGzL4H8/maxresdefault.jpg',
      postedAt: '4 dias atrás',
      duration: '25:45',
    },
    {
      id: 'oDqA7f_2_A0',
      title: 'Why the Arm Triangle is the King of Submissions',
      channel: 'BJJ Scout',
      thumbnail: 'https://img.youtube.com/vi/oDqA7f_2_A0/maxresdefault.jpg',
      postedAt: '6 horas atrás',
      duration: '14:20',
    },
    {
      id: 'L0C2_QZ3s-Q',
      title: 'Fighter Salary: The Truth About MMA Money',
      channel: 'Ariel Helwani',
      thumbnail: 'https://img.youtube.com/vi/L0C2_QZ3s-Q/maxresdefault.jpg',
      postedAt: '12 horas atrás',
      duration: '32:00',
    },
  ],
};
